name: Gradle CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "22"

      - name: Grant executive premissions for gradlew
        run: chmod +x gradlew

      - name: Run Build
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test